language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=3.6 }
    - { os: linux, env: PYTHON_VERSION=3.7 }

env:
  global:
  - ENCRYPTION_LABEL: "fa70a735182b"
  - COMMIT_AUTHOR_EMAIL: "andrew.z.summers@gmail.com"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n test-environment python=$PYTHON_VERSION
  - source activate test-environment
  - conda install -c conda-forge pytest
  - conda install --only-deps -c mosdef foyer
  - pip install git+https://github.com/mosdef-hub/foyer
  - pip install -e .

script:
  - py.test -v

after_success:
  - codecov
