language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=3.6 }
    - { os: linux, env: PYTHON_VERSION=3.7 }

env:
  global:
  - ENCRYPTION_LABEL: "fa70a735182b"
  - COMMIT_AUTHOR_EMAIL: "andrew.z.summers@gmail.com"

install:
  - source devtools/travis-ci/install_conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda create -n test-environment python=$PYTHON_VERSION --file requirements.txt
  - source activate test-environment
  - conda uninstall -y --force foyer
  - pip install git+https://github.com/mosdef-hub/foyer
  - pip install -e .

script:
  - py.test -v

after_success:
  - codecov
